/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package video;

import com.xuggle.xuggler.demos.VideoImage;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.beans.XMLDecoder;
import java.io.BufferedInputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author goryunov
 */
public class MainFrame extends javax.swing.JFrame {

    private Foo model = new Foo();
    private Hopfield net;
    
    private MainFrame frame = this;
    
    private boolean active = true;
    
    public void setActive() {
        //active = true;
        //buttonFileChooser.setEnabled(true);
        setState(true);
    }
    
    public void setPassive() {
        //active = false;
        setState(false);
    }
    
    private void setState(boolean state) {
        buttonFileChooser.setEnabled(state);
        buttonStart.setEnabled(state);
        buttonSimpleView.setEnabled(state);
    }
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        net = new Hopfield(5, 5);
        net.learn();
        //net.test();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonFileChooser = new javax.swing.JButton();
        buttonStart = new javax.swing.JButton();
        loadingLabel = new javax.swing.JLabel();
        buttonSimpleView = new javax.swing.JButton();
        panel = new video.VideoPanel();
        stopButton = new javax.swing.JButton();
        generated = new video.VideoPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Видео в символы");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        buttonFileChooser.setText("Выбрать файл");
        buttonFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFileChooserActionPerformed(evt);
            }
        });

        buttonStart.setText("Обработать");
        buttonStart.setEnabled(false);
        buttonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStartActionPerformed(evt);
            }
        });

        loadingLabel.setText(" ");

        buttonSimpleView.setText("Обычный просмотр");
        buttonSimpleView.setEnabled(false);
        buttonSimpleView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpleViewActionPerformed(evt);
            }
        });

        panel.setPreferredSize(new java.awt.Dimension(480, 320));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        stopButton.setText("Стоп");
        stopButton.setEnabled(false);
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        generated.setPreferredSize(new java.awt.Dimension(480, 320));

        javax.swing.GroupLayout generatedLayout = new javax.swing.GroupLayout(generated);
        generated.setLayout(generatedLayout);
        generatedLayout.setHorizontalGroup(
            generatedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        generatedLayout.setVerticalGroup(
            generatedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonFileChooser)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonStart))
                            .addComponent(loadingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSimpleView)
                        .addGap(43, 43, 43)
                        .addComponent(stopButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(generated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFileChooser)
                    .addComponent(buttonStart)
                    .addComponent(buttonSimpleView)
                    .addComponent(stopButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loadingLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(generated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*public void paint(Graphics g) {
	g.setColor(Color.RED);

        g.fillRect(0, 0, getWidth(), getHeight());
    }*/
    
    private void buttonFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFileChooserActionPerformed
        if (active==false)
            return;
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogType(JFileChooser.OPEN_DIALOG);
        //chooser.addChoosableFileFilter(new FileChooserFilter());
        chooser.setAcceptAllFileFilterUsed(true);
        chooser.setDialogTitle("Открыть ...");

        loadingLabel.setText("Проверка файла...");
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            try {
                model.fileChecker(chooser.getSelectedFile());
                this.repaint();
                loadingLabel.setText("Файл подходит для обработки");
                buttonStart.setEnabled(true);
                buttonSimpleView.setEnabled(true);
                /*FileInputStream fis;
                if (chooser.getSelectedFile().getName().toLowerCase().endsWith(".xml"))
                    fis = new FileInputStream(chooser.getSelectedFile().getPath());
                else fis = new FileInputStream(chooser.getSelectedFile().getPath()+".xml");

		BufferedInputStream bis = new BufferedInputStream(fis);
		XMLDecoder xmlDecoder = new XMLDecoder(bis);

                try {
                    Point mb1 = (Point)xmlDecoder.readObject();
                    redactorPanel.getModel().setStartPoint(mb1);
                    Point mb2 = (Point) xmlDecoder.readObject();
                    redactorPanel.getModel().setFinalPoint(mb2);
                    Integer mb3 = (Integer)xmlDecoder.readObject();
                    redactorPanel.getModel().setSelectedFigureIndex(mb3);
                    Color mb4 = (Color)xmlDecoder.readObject();
                    redactorPanel.getModel().setSelectedFigureColor(mb4);
                    ArrayList<ColouredFigure> mb5 = (ArrayList<ColouredFigure>) xmlDecoder.readObject();
                    redactorPanel.getModel().setColFigures(mb5);
                    Color mb6 = (Color) xmlDecoder.readObject();
                    redactorPanel.getModel().setNewFiguresColor(mb6);
                    xmlDecoder.close();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Ошибка при чтении файла!",
                        "Ошибка", JOptionPane.ERROR_MESSAGE);
                    return;
                } finally {
                    xmlDecoder.close();
                    //redactorPanel.repaint();
                }*/
            /*} catch (FileNotFoundException e) {
                JOptionPane.showMessageDialog(this, "Файл не найден!",
                    "Ошибка", JOptionPane.ERROR_MESSAGE);                
                return; 
            }*/
            } catch (Exception e) {
                loadingLabel.setText("Ошибка формата файла");
                buttonStart.setEnabled(false);
                buttonSimpleView.setEnabled(false);
                JOptionPane.showMessageDialog(this, e.getMessage(),
                    "Ошибка", JOptionPane.ERROR_MESSAGE); 
            } /*finally {
                loadingLabel.setText("Ошибка формата файла");
            }*/
        } else {
            //loadingLabel.setText("");
        }
    }//GEN-LAST:event_buttonFileChooserActionPerformed

    private void buttonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStartActionPerformed
        if (active==false)
            return;
        try {
            //model.process();
            //model.processview(panel, generated, frame);
            //loadingLabel.setText("Обработка файла завершена!");
            
            class HelloThread extends Thread {
                public void run() {
                    stopButton.setEnabled(true);
                    frame.repaint();
                    model.processview(panel, generated, frame);
                    loadingLabel.setText("Обработка файла завершена!");
                    stopButton.setEnabled(false);
                }
            }
            Thread t = new HelloThread();
            t.start();
        } catch (Exception e) {
                loadingLabel.setText("Обработка файла завершилась ошибкой");
                JOptionPane.showMessageDialog(this, e.getMessage(),
                    "Ошибка", JOptionPane.ERROR_MESSAGE);                
        }
    }//GEN-LAST:event_buttonStartActionPerformed

    private void buttonSimpleViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpleViewActionPerformed
        if (active==false)
            return;
        try {
            //model.simpleview(panel);
            
            class HelloThread extends Thread {

                public void run() {
                    //System.out.println("Hello, world!");
                    stopButton.setEnabled(true);
                    frame.repaint();
                    model.simpleview(panel, frame);
                    stopButton.setEnabled(false);
                }
            }
    


                Thread t = new HelloThread();
                t.start();
                /*try {
                    t.join();
                } catch (InterruptedException e) {
                    System.err.println("errrrrrr");
                }*/

        } catch (Exception e) {
                loadingLabel.setText("Просмотр файла завершился ошибкой");
                JOptionPane.showMessageDialog(this, e.getMessage(),
                    "Ошибка", JOptionPane.ERROR_MESSAGE);                
        }
        //openJavaWindow();
            //new org.jdesktop.swingx.JXDialog(this, new JPanel()).setVisible(true);
    }//GEN-LAST:event_buttonSimpleViewActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        model.stop();
    }//GEN-LAST:event_stopButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        model.stop();
    }//GEN-LAST:event_formWindowClosing
  
    /*private static VideoImage mScreen = null;
    
    private static void openJavaWindow() {
        mScreen = new VideoImage();
    }*/
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonFileChooser;
    private javax.swing.JButton buttonSimpleView;
    private javax.swing.JButton buttonStart;
    private video.VideoPanel generated;
    private javax.swing.JLabel loadingLabel;
    private video.VideoPanel panel;
    private javax.swing.JButton stopButton;
    // End of variables declaration//GEN-END:variables
}
